#!/usr/bin/env bash
#Script that transfers a file from our client to a server

# Check if all 4 parameters are provided
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
path_to_file=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$path_to_file" "$username@$server_ip":~/ 

# Check if scp command executed successfully
if [ $? -eq 0 ]; then
    echo "File transferred successfully to $username@$server_ip:~/"
else
    echo "Error transferring file."
fi
