#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string

# Install nginx
apt-get update -y
apt-get install nginx -y

# Configure nginx
echo "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    location / {
        echo 'Hello World!' > index.html;
        echo 'Content-Type: text/html' >> index.html;
        echo '' >> index.html;
        echo '' >> index.html;
    }
}" > /etc/nginx/sites-available/default

# Restart nginx
service nginx restart
