#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.
#+    Returns a page containing "Hello World!" when queried
#++    at the root with a curl GET request.

# Update package index
apt-get update

# Install Nginx
apt-get install -y nginx

# Create a configuration file for the redirection
echo "server {
    listen 80;
    listen [::]:80;

    server_name _;

    location /redirect_me {
        return 301 http://example.com/new-page;
    }

    location / {
        root /var/www/html;
        index index.html index.htm;
    }
}" > /etc/nginx/sites-available/redirect

# Create a symbolic link to enable the new configuration
ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/

# Remove default Nginx configuration
rm /etc/nginx/sites-enabled/default

# Test Nginx configuration
nginx -t

# Reload Nginx to apply changes
service nginx reload
