#!/usr/bin/env bash
# Installs nginx web server

# Step 1: Install Nginx
sudo apt update
sudo apt install nginx -y

# Step 2: Create a custom 404 page
sudo tee /var/www/html/404.html <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page</p>
</body>
</html>
EOF

# Step 3: Configure Nginx to use the custom 404 page
sudo tee /etc/nginx/sites-available/custom_404 <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    # Redirect all other requests to the main server
    location / {
        return 301 https://zakesmatsimbe.tech;
    }
}
EOF

# Step 4: Enable the site configuration
sudo ln -s /etc/nginx/sites-available/custom_404 /etc/nginx/sites-enabled/

# Step 5: Test Nginx configuration
sudo nginx -t

# Step 6: Restart Nginx to apply changes
sudo systemctl restart nginx
