#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
# redirection must be a “301 Moved Permanently”
# Include a custom 404 page that contains a string

# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install -y nginx

# Change ownership of /var/www to user 'ubuntu'
sudo chown -R ubuntu /var/www

# Create index file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Add 301 redirect configuration to Nginx default site configuration
sudo sed -i "30i\\$ADD301_REDIRECT" /etc/nginx/sites-available/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html >/dev/null

# Add custom 404 page configuration to Nginx default site configuration
sudo sed -i "47i\\$PATTERN$ADD404_NOTFOUND" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

