#!/usr/bin/env bash

# Update package lists and install Nginx
apt-get update -y
apt-get install nginx -y

# Create a custom index.html file
echo "Hello World!" > /usr/share/nginx/html/index.html

# Create a custom 404 page
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Define custom configurations
custom_config1="error_page 404 /custom_404.html;\n\tlocation /redirect_me {\n\t\treturn 301 \$scheme://www.google.com;}"
custom_config2="add_header X-Served-By \$hostname;"

# Update Nginx default site configuration
sed -i "/server {/a \\$custom_config1" /etc/nginx/sites-available/default
sed -i "/server {/a \\$custom_config2" /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
