#!/usr/bin/env bash

# Get the hostname of the server
hostname=$(hostname)

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Configure Nginx to add custom header
cat <<EOF > /etc/nginx/conf.d/custom_response_header.conf
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    location / {
        add_header X-Served-By $hostname;
        root /usr/share/nginx/html;
        index index.html index.htm;
    }
}
EOF

# Remove the default configuration if it exists
rm /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
systemctl restart nginx

