#!/usr/bin/env bash

# Get the hostname
hostname=$(hostname)

# Install Nginx
apt-get update -y
apt-get install nginx -y

# Configure Nginx to add custom header
new_string="add_header X-Served-By $hostname;"
sudo sed -i "/^server \{/a $new_string" /etc/nginx/sites-available/default

# Test Nginx configuration
nginx -t

# Restart Nginx to apply changes
systemctl restart nginx
