#!/usr/bin/env bash
# Installing new server to serve content

nginx -t
nginx_pid=$(pidof nginx)
occupied_port=$(netstat -tln | grep ':80')

if [[ -n "$occupied_port" || -z "$nginx_pid" ]]; then
    systemctl restart nginx
fi
