#!/usr/bin/env bash
# Installing new server to serve content
#./0-nginx_likes_port_80
#echo "hi" > /var/run/nginx.pid
#echo "hi" > /run/nginx.pid

nginx -t && systemctl restart nginx
if ! pidof nginx &> /dev/null; then
  systemctl start nginx
fi
