#!/usr/bin/env bash
# Displays a list of currently running processes.
# Define the header for the output
printf "%-10s %-5s %-5s %-7s %-7s %-7s %-7s %-10s %-10s %s\n" "USER" "PID" "%CPU" "%MEM" "VSZ" "RSS" "TTY" "STAT" "START" "COMMAND"

# Use ps command to display processes
ps axo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,comm --forest
