#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
id=$(pgrep "bash ./4-to_infinity_and_beyond" -f)

# Terminate the infinate process
if [ -n "$id" ]
then
  kill -15 "$id"
fi
