#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
#pid=$(pgrep 4-to_infinity_and_beyond)
pid=$(pgrep -f "4-to_infinity_and_beyond")

# Check if the process exists
if [ -n "$pid" ]; then
    # If it exists, kill the process
    kill "$pid"
    echo "Terminated"
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
