#!/usr/bin/env bash
# Stops 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep 4-to_infinity_and_beyond)

# Check if the process exists
if [ -n "$pid" ]; then
    # If it exists, stop the process by sending a termination signal to its process group
    pkill -TERM -g "$pid"
    echo "Terminated"
else
    echo "Process 4-to_infinity_and_beyond is not running."
fi
