#!/usr/bin/env bash
# Displaying "Best School" 10 times 9th element display "Best School" and then "Hi"

#!/bin/bash

count=0

while [ $count -lt 10 ]; do
    if [ $count -eq 8 ]; then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    count=$((count + 1))
done
