#!/usr/bin/env bash
# Displaying the The content of the current directory
# Loop through each file in the current directory
for file in *; do
    # Check if the file is not hidden
    if [[ ! "$file" == .* ]]; then
        # Extract the part of the name after the first dash
        name_part=$(echo "$file" | cut -d'-' -f2-)
        # Print the name part
        echo "$name_part"
    fi
done
