#!/usr/bin/env bash
[ ! -x "$(command -v nginx)" ] && echo "NGINX is not installed. Please install NGINX before running this script." && exit 1
[ ! -f /etc/nginx/sites-available/default ] && echo "Default NGINX configuration file not found." && exit 1
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx stop
