#!/usr/bin/env bash
# Generate an RSA key pair with a 4096-bit key length and a passphrase

# Generate RSA key pair with specified parameters
ssh-keygen -f ~/.ssh/school -b 4096 -N "betty"

# Rename private key file to "school" without extension
mv ~/.ssh/school.pem ~/.ssh/school

echo "RSA key pair created successfully!"

