#!/usr/bin/env bash
# Generate an RSA key pair with a 4096-bit key length and a passphrase


# Generate RSA key pair with specified parameters
openssl genpkey -algorithm RSA -out school.pem -aes256 -pass pass:betty -pkeyopt rsa_keygen_bits:4096
